// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"xmu_roll_call/app"
	"xmu_roll_call/app/client"
	"xmu_roll_call/app/encrypt"
	"xmu_roll_call/app/login"
	"xmu_roll_call/app/roll_call"
)

// Injectors from wire.go:

func InitializeLoginImpl() *login.LoginImpl {
	restyClient := client.NewClient()
	encryptImpl := encrypt.NewEncryptImpl()
	loginImpl := login.NewLoginImpl(restyClient, encryptImpl)
	return loginImpl
}

func InitializeRollCallImpl() *roll_call.RollCallImpl {
	restyClient := client.NewClient()
	encryptImpl := encrypt.NewEncryptImpl()
	loginImpl := login.NewLoginImpl(restyClient, encryptImpl)
	rollCallImpl := roll_call.NewRollCallImpl(restyClient, loginImpl)
	return rollCallImpl
}

func InitializeAppImpl() *app.AppImpl {
	restyClient := client.NewClient()
	encryptImpl := encrypt.NewEncryptImpl()
	loginImpl := login.NewLoginImpl(restyClient, encryptImpl)
	rollCallImpl := roll_call.NewRollCallImpl(restyClient, loginImpl)
	appImpl := app.NewAppImpl(loginImpl, rollCallImpl)
	return appImpl
}
