// Code generated by Wire. DO NOT EDIT.
//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"xmu_roll_call/app/client"
	"xmu_roll_call/app/encrypt"
	"xmu_roll_call/app/login"
)

// Injectors from wire.go:

func InitializeLoginImpl() *login.LoginImpl {
	restyClient := client.NewClient()
	encryptImpl := encrypt.NewEncryptImpl()
	loginImpl := login.NewLoginImpl(restyClient, encryptImpl)
	return loginImpl
}
